CREATE TABLE labrastro_message_feedback (
    installation_id uuid NOT NULL,
    inbound_message_id text NOT NULL,
    workspace_id uuid NOT NULL,
    delivery_id uuid NOT NULL,
    quoted_message_id text NOT NULL,
    sender_id text NOT NULL,
    user_id uuid NOT NULL,
    installation_agent_id uuid NOT NULL,
    chat_id text NOT NULL,
    thread_id text NOT NULL DEFAULT '',
    content text NOT NULL,
    kind text NOT NULL CHECK (kind IN ('comment', 'report', 'refusal')),
    issue_id uuid,
    parent_comment_id uuid,
    comment_id uuid,
    issue_revision bigint NOT NULL DEFAULT 0,
    chat_session_id uuid,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'complete', 'rejected')),
    notice text NOT NULL DEFAULT '',
    ack_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    acknowledged_at timestamptz,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
